# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('Dia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Masaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masajes.Cliente')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masajes.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Empleados',
            field=models.ManyToManyField(through='masajes.Masaje', to='masajes.Empleado'),
        ),
    ]
